Traceback (most recent call last):
  File "/home/runner/.virtualenvs/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.virtualenvs/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.virtualenvs/.venv/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.virtualenvs/.venv/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/.virtualenvs/.venv/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.virtualenvs/.venv/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.virtualenvs/.venv/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load Pywr-DRB simulation flow results at major nodes
simulated_flows = get_pywr_results('./output_data/', 
                                   model = 'obs_pub', 
                                   results_set = 'major_flow')

# Report the size of the retrieved data
print(f'The resulting dataframe has {simulated_flows.shape[0]} days of data at {simulated_flows.shape[1]} different nodes.')

# Display the data
simulated_flows.tail(2)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m [38;5;66;03m# Load Pywr-DRB simulation flow results at major nodes[39;00m
[0;32m----> 2[0m simulated_flows [38;5;241m=[39m [43mget_pywr_results[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m./output_data/[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m
[1;32m      3[0m [43m                                   [49m[43mmodel[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mobs_pub[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m
[1;32m      4[0m [43m                                   [49m[43mresults_set[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mmajor_flow[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      6[0m [38;5;66;03m# Report the size of the retrieved data[39;00m
[1;32m      7[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mThe resulting dataframe has [39m[38;5;132;01m{[39;00msimulated_flows[38;5;241m.[39mshape[[38;5;241m0[39m][38;5;132;01m}[39;00m[38;5;124m days of data at [39m[38;5;132;01m{[39;00msimulated_flows[38;5;241m.[39mshape[[38;5;241m1[39m][38;5;132;01m}[39;00m[38;5;124m different nodes.[39m[38;5;124m'[39m)

File [0;32m~/work/Pywr-DRB/Pywr-DRB/drb_make_figs.py:58[0m, in [0;36mget_pywr_results[0;34m(output_dir, model, results_set, scenario)[0m
[1;32m     45[0m [38;5;28;01mdef[39;00m [38;5;21mget_pywr_results[39m(output_dir, model, results_set[38;5;241m=[39m[38;5;124m'[39m[38;5;124mall[39m[38;5;124m'[39m, scenario [38;5;241m=[39m [38;5;241m0[39m):
[1;32m     46[0m [38;5;250m    [39m[38;5;124;03m'''[39;00m
[1;32m     47[0m [38;5;124;03m    Gathers simulation results from Pywr model run and returns a pd.DataFrame. [39;00m
[1;32m     48[0m [38;5;124;03m    [39;00m
[0;32m   (...)[0m
[1;32m     56[0m [38;5;124;03m    :return:[39;00m
[1;32m     57[0m [38;5;124;03m    '''[39;00m
[0;32m---> 58[0m     [38;5;28;01mwith[39;00m [43mh5py[49m[38;5;241;43m.[39;49m[43mFile[49m[43m([49m[38;5;124;43mf[39;49m[38;5;124;43m'[39;49m[38;5;132;43;01m{[39;49;00m[43moutput_dir[49m[38;5;132;43;01m}[39;49;00m[38;5;124;43mdrb_output_[39;49m[38;5;132;43;01m{[39;49;00m[43mmodel[49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m.hdf5[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m f:
[1;32m     59[0m         keys [38;5;241m=[39m [38;5;28mlist[39m(f[38;5;241m.[39mkeys())
[1;32m     60[0m         first [38;5;241m=[39m [38;5;241m0[39m

File [0;32m~/.virtualenvs/.venv/lib/python3.8/site-packages/h5py/_hl/files.py:567[0m, in [0;36mFile.__init__[0;34m(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, fs_strategy, fs_persist, fs_threshold, fs_page_size, page_buf_size, min_meta_keep, min_raw_keep, locking, alignment_threshold, alignment_interval, meta_block_size, **kwds)[0m
[1;32m    558[0m     fapl [38;5;241m=[39m make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0,
[1;32m    559[0m                      locking, page_buf_size, min_meta_keep, min_raw_keep,
[1;32m    560[0m                      alignment_threshold[38;5;241m=[39malignment_threshold,
[1;32m    561[0m                      alignment_interval[38;5;241m=[39malignment_interval,
[1;32m    562[0m                      meta_block_size[38;5;241m=[39mmeta_block_size,
[1;32m    563[0m                      [38;5;241m*[39m[38;5;241m*[39mkwds)
[1;32m    564[0m     fcpl [38;5;241m=[39m make_fcpl(track_order[38;5;241m=[39mtrack_order, fs_strategy[38;5;241m=[39mfs_strategy,
[1;32m    565[0m                      fs_persist[38;5;241m=[39mfs_persist, fs_threshold[38;5;241m=[39mfs_threshold,
[1;32m    566[0m                      fs_page_size[38;5;241m=[39mfs_page_size)
[0;32m--> 567[0m     fid [38;5;241m=[39m [43mmake_fid[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mmode[49m[43m,[49m[43m [49m[43muserblock_size[49m[43m,[49m[43m [49m[43mfapl[49m[43m,[49m[43m [49m[43mfcpl[49m[43m,[49m[43m [49m[43mswmr[49m[38;5;241;43m=[39;49m[43mswmr[49m[43m)[49m
[1;32m    569[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(libver, [38;5;28mtuple[39m):
[1;32m    570[0m     [38;5;28mself[39m[38;5;241m.[39m_libver [38;5;241m=[39m libver

File [0;32m~/.virtualenvs/.venv/lib/python3.8/site-packages/h5py/_hl/files.py:231[0m, in [0;36mmake_fid[0;34m(name, mode, userblock_size, fapl, fcpl, swmr)[0m
[1;32m    229[0m     [38;5;28;01mif[39;00m swmr [38;5;129;01mand[39;00m swmr_support:
[1;32m    230[0m         flags [38;5;241m|[39m[38;5;241m=[39m h5f[38;5;241m.[39mACC_SWMR_READ
[0;32m--> 231[0m     fid [38;5;241m=[39m [43mh5f[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mflags[49m[43m,[49m[43m [49m[43mfapl[49m[38;5;241;43m=[39;49m[43mfapl[49m[43m)[49m
[1;32m    232[0m [38;5;28;01melif[39;00m mode [38;5;241m==[39m [38;5;124m'[39m[38;5;124mr+[39m[38;5;124m'[39m:
[1;32m    233[0m     fid [38;5;241m=[39m h5f[38;5;241m.[39mopen(name, h5f[38;5;241m.[39mACC_RDWR, fapl[38;5;241m=[39mfapl)

File [0;32mh5py/_objects.pyx:54[0m, in [0;36mh5py._objects.with_phil.wrapper[0;34m()[0m

File [0;32mh5py/_objects.pyx:55[0m, in [0;36mh5py._objects.with_phil.wrapper[0;34m()[0m

File [0;32mh5py/h5f.pyx:106[0m, in [0;36mh5py.h5f.open[0;34m()[0m

[0;31mFileNotFoundError[0m: [Errno 2] Unable to open file (unable to open file: name = './output_data/drb_output_obs_pub.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = './output_data/drb_output_obs_pub.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

